Model
Uni-Sopron/dtr-o21-beadando-kebelei-forma1 pull request #3
Opened 2022-01-11 12:24 UTC by kebeleicsaba

2022-01-11 12:30 UTC, kebeleicsaba commented on model.mod
> +# If use[lap1, tyre] == 1 and use[lap2, tyre] == 1, then lap2=1 ∑ lap1 tyre_change[lap] >= 1
Itt olyan probléma ütköztem, hogy meg kell adnom a sum-ot két intervallum között (Vagyis, hogy ha túllépi a lap1 és a lap2 közötti különbség a life_time-ot akkor biztosan kellet legalább 1 kerékcserének lennie lap1 és lap2 között). Viszont nem tudom ennek a szintaktikáját. :(

2022-01-11 17:18 UTC, hegyhati commented on model.mod
> +# If use[lap1, tyre] == 1 and use[lap2, tyre] == 1, then lap2=1 ∑ lap1 tyre_change[lap] >= 1
```ampl
sum{lap in Laps : lap >= lap1 && lap < lap2} tyre_change[lap] >=1
```

Erre gondolsz?

2022-01-11 17:55 UTC, hegyhati requested changes

2022-01-11 17:55 UTC, hegyhati commented on model.mod
> +set race_length2 := 1..number_of_laps-1;
ezt nem vezetnem be:
1) semmit sem mond ez a neve
2) osszesen ket helyen hasznalod, ertelmesebb lenne, ha ott lenne `lap in race_length2` helyett `lap in race_length : lap != number_of_laps`

2022-01-11 17:55 UTC, hegyhati commented on model.mod
> +# If use[lap, tyre1] == 1 && use[lap+1, tyre2] == 1, then tyre_change[lap] = 1 and used_compound[tyre2] = 1;
a `used_compound`-ot szerintem kulon korlatozasban akarjuk beallitani, nem itt.

2022-01-11 17:55 UTC, hegyhati commented on model.mod
> +s.t. Tyre_compound_change{lap in race_length2, tyre1 in tyre_compounds, tyre2 in tyre_compounds}:
sanszos, hogy ki akarnad kotni hogy `tyre1 != tyre2`

2022-01-11 17:55 UTC, hegyhati commented on model.mod
> +    tyre_change[lap] + used_compound[tyre2] <= 2 + M * (2 - use[lap, tyre1] - use[lap+1, tyre2]);
Ez a korlatozas nem csinal semmit. A bal oldal lehet 0,1,2, a jobb oldal meg 2 vagy vegtelen. Szoval ez mindig igaz lesz.

Ezt gondold at.

2022-01-12 16:30 UTC, kebeleicsaba commented
Amennyire tudtam javítottam a dolgon. A used_compound nem igazán akar működni, azt nem étem miért. :(

2022-01-13 16:07 UTC, kebeleicsaba commented
Megoldódott az előző problémám. 😁 Így valamikor rá tudnál nézni a modelre, hogy szerinted is jó-e?

2022-01-17 13:10 UTC, hegyhati requested changes
ok, `race_length` => `Laps`

2022-01-17 21:37 UTC, merged