Model with degradation logic
Uni-Sopron/dtr-o21-beadando-kebelei-forma1 pull request #4
Opened 2022-01-17 21:55 UTC by kebeleicsaba

2022-01-17 22:09 UTC, kebeleicsaba commented
Ha elég kevés a körök száma (pl.: 10), akkor arra elvileg működik, de ha sok kör van, valóban piszok lassú...

2022-01-18 14:09 UTC, hegyhati requested changes

2022-01-18 14:09 UTC, hegyhati commented on model_2.mod
> +    lap_time[lap] >= tyre_compounds_base_lap_time[tyre] - M * (1 - use[lap, tyre]);
mivel a `lap_time` mindig no, ezert szerintem ez lehetne siman `>= tyre_compounds_base_lap_time[tyre] * use[lap, tyre]`. De ez amugy minden lap-re igaz egyebkent, mert mindig no csak.

2022-01-18 14:09 UTC, hegyhati commented on model_2.mod
> +    tyre_compounds_base_lap_time[tyre] + tyre_change_time
a tyre change time-ot ide nem tennem bele, mert a akkor a kovetkezo korben is korlatoz ezzel.

2022-01-18 14:09 UTC, hegyhati commented on model_2.mod
> +    - M * (1 - use[lap, tyre]);
ez viszont csak akkor, ha nem volt valtas, tehat a change az 0

2022-01-18 14:09 UTC, hegyhati commented on model_2.mod
> +    sum{lap in laps} lap_time[lap];
a change time-okat tovabbra is ide.

2022-01-19 22:49 UTC, merged